#! /bin/sh

while [ $# -gt 0 ] ; do
    pattern=$1
    target=$(which "$pattern" 2> /dev/null)
    if [ $? -eq 0 ] ; then
        exec e "$target"
    else
        results="$(find -L "$XDG_BIN_DIR" -maxdepth 1 -type f -iname "*${pattern}*" -print0 | xargs -0)"
        if [ -n "$results" ] ; then
            exec e $results
        fi
    fi
    shift
done
