#! /usr/bin/env python3

from datetime import datetime
import time
import os
import ephem

def utc_to_local(utc):
    epoch = time.mktime(utc.timetuple())
    offset = datetime.fromtimestamp(epoch) - datetime.utcfromtimestamp(epoch)
    return utc + offset

home = ephem.Observer()
home.lat = os.environ['LATITUDE']
home.lon = os.environ['LONGITUDE']
home.elevation = float(os.environ['ELEVATION'])

sun = ephem.Sun()
sun.compute(home)
sun_rise = utc_to_local(home.next_rising(sun).datetime())
sun_set = utc_to_local(home.next_setting(sun).datetime())
fmt = "%H:%M"

print('{}\n{}'.format(sun_rise.strftime(fmt), sun_set.strftime(fmt)))
