#! /bin/sh

[ $# -lt 2 ] && exit 1

cnt=1
input=$1
ext=${input##*.}
base=${input%.*}
shift

while [ $# -gt 0 ] ; do
    begin=$1
    shift
    end=$1
    ffmpeg -i "$input" -c copy -ss "$begin" -to "$end" "${base}-$(printf '%03d' $cnt).$ext"
    shift
    cnt=$((cnt + 1))
done
