#! /bin/sh

tmp_dir=$(mktemp -d /tmp/mutt.XXXX)

# Decompress the attachments of the message read on stdin
munpack -C "$tmp_dir"
# Rename foo.jpg.1 to foo.1.jpg
rename 's/^(.*)\.([^.]+)\.(\d+)$/$1.$3.$2/' "$tmp_dir"/*
# Try to extract images from PPS documents
find -L "$tmp_dir" -iname "*.pps" -exec ppsei {} +
# Find and open documents
find -EL "$tmp_dir" -iregex ".*\.(pdf|e?ps)" -exec dr {} +
# Find and open images
find -EL "$tmp_dir" -iregex '.*\.(jpe?g|png|gif|tif?f|bmp)' -exec iv {} +
# Find and open movies
find -EL "$tmp_dir" -iregex '.*\.(mp4|avi|mov|mpe?g|wmv|flv)' -exec vp {} +
# Find and open unnamed files
find -EL "$tmp_dir" -iregex '.*part[0-9]+$' -exec o {} +
